# Generated by Django 5.2.5 on 2025-08-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_featrued_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featrued_pic',
            new_name='featured_pic',
        ),
    ]
